server:
  port: 8888
---
spring:
  profiles: ide
  application:
    name: CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/clustercamp/springcloud-java.git
          searchPaths: /configs/{application}
#  rabbitmq:
#    host: localhost
#    username: springcloud
#    password: springcloud
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'