apiVersion: v1
kind: ConfigMap
metadata:
  name: springcloud-config
  namespace: springcloud
data:
  application.yaml: |-
    server:
      port: 8888
    spring:
      application:
        name: CONFIG
      boot:
          admin:
            client:
              url: http://eureka.springcloud.svc.cluster.local:8761/admin
              instance:
                preferIp: true
      cloud:
        config:
          server:
            git:
              uri: https://github.com/clustercamp/springcloud-java.git
              searchPaths: /configs/{application}
      rabbitmq:
        host: rabbitmq.springcloud.svc.cluster.local
        port: 5672
        username: springcloud
        password: springcloud
    management:
      metrics:
        tags:
          application: ${spring.application.name}
      endpoint:
        metrics:
          enabled: true
      endpoints:
        jmx:
          exposure:
            include: '*'
        web:
          exposure:
            include: '*'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: springcloud
  labels:
    framework: springcloud
    app: springcloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      springcloud: config
  template:
    metadata:
      labels:
        springcloud: config
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '8888'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
        - name: app
          image: dockercamp/springcloud-config:1.3.0
          ports:
            - containerPort: 8888
          env:
            - name: spring.config.location
              value: /config/
            - name: spring.cloud.config.server.git.username
              valueFrom:
                secretKeyRef:
                  name: github
                  key: username
            - name: spring.cloud.config.server.git.password
              valueFrom:
                secretKeyRef:
                  name: github
                  key: password
          volumeMounts:
            - name: application-config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: application-config
          configMap:
            name: springcloud-config
            items:
              - key: application.yaml
                path: application.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: config
  namespace: springcloud
spec:
  selector:
    springcloud: config
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: config
  namespace: springcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    external-dns.alpha.kubernetes.io/target: home.cluster.camp
spec:
  rules:
    - host: config.cluster.camp
      http:
        paths:
          - path: /
            backend:
              serviceName: config
              servicePort: 8888

